### ISSUE TITLE
strip slashes

### ISSUE THREAD

**Issue by rottmann** [mikeedwards/po2json#14]
A .po file generated with Virtaal add slashes:

test.po
```
msgid ""
"Hallo \\\"Welt\\\", das ist ein Test"
msgstr ""
"Hello \\\"World\\\", this is a test"
```

po2json add more slashes:

test.json
```json
"Hallo \\\\\"Welt\\\\\", das ist ein Test": [
   null,
   "Hello \\\\\"World\\\\\", this is a test"
],
```

**Comment by mikeedwards** [comment]
Just tested this with recent versions against the test.po file there, and the slashed are now behaving as the should be.
