### ISSUE TITLE
Jed's changed its format, 'jed' format no longer compatible

### ISSUE THREAD

**Issue by emosesSfdc** [mikeedwards/po2json#31]
Jed was updated so that it no longer has the first "null" in the translated string arrays, i.e., it used to look like 

    "key" : [null, "value", "values] //etc.

but now looks like

    "key" : ["value", "values"]

Jed format needs to be updated to match, or possibly a new jed1.x format

**Comment by mikeedwards** [comment]
Hey @Sinewyk @emosesSfdc , po2json 0.4.0 brings in the new option. Let me know if there are any new or lingering issues

**Comment by Sinewyk** [comment]
You should close this then, np for me.
