### ISSUE TITLE
Domain not included in Json file breaks Jed

### ISSUE THREAD

**Issue by guioconnor** [mikeedwards/po2json#40]
I started testing Jed today for a project that needs translations both client side and server side, and I'm using po2json to convert from po files.

I've got some example .po files in the following locations (I'm presuming they are valid .po files)

http://svn.opensuse.org/svn/opensuse-i18n/trunk/
https://github.com/drupal/drupal/blob/7.x/modules/locale/tests/translations/test.xx.po

However, the compiled file doesn't work straight away, it needs to be amended with some extra domain info (as per the JED documentation) to make it work, even when passing the `-d` option.

I get the same problem regarding of converting in the command line or inside node.js.

**Comment by mikeedwards** [comment]
Are you still having this issue after the recent updates for Jed? If not, I'll close the ticket.

**Comment by guioconnor** [comment]
@mikeedwards I have not used JED since, so I don't have any data on the error.

**Comment by mikeedwards** [comment]
Ok, I'm closing for now. But feel free to open a new issue if you run into this again with the latest version.
