### ISSUE TITLE
Wrong output for Jed

### ISSUE THREAD

**Issue by patrickfournier** [mikeedwards/po2json#43]
I am using po2json to create JSON files for use with Jed. My po looks like this:

```
# French translations for PACKAGE package.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-01-05 16:44-0500\n"
"PO-Revision-Date: 2016-01-05 16:48-0500\n"
"Last-Translator: Patrick Fournier <...>\n"
"Language-Team: French\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ASCII\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ../app/routes/content.js:8
msgid "Content"
msgstr "Contenu"

#: ../app/routes/content.js:10
msgid "Potato"
msgid_plural "Potatoes"
msgstr[0] "Patate"
msgstr[1] "Patates"
```

The generated JSON file is:

```
{
   "domain": "messages",
   "locale_data": {
      "messages": {
         "": {
            "domain": "messages",
            "plural_forms": "nplurals=2; plural=(n > 1);",
            "lang": "fr"
         },
         "Content": [
            null,
            "Contenu"
         ],
         "Potato": [
            "Potatoes",
            "Patate",
            "Patates"
         ]
      }
   }
}
```

This does not work with Jed because there is an extra item at the beginning of each translation list, which correspond to the `msgid_plural` key. The expected JSON would be:

```
{
   "domain": "messages",
   "locale_data": {
      "messages": {
         "": {
            "domain": "messages",
            "plural_forms": "nplurals=2; plural=(n > 1);",
            "lang": "fr"
         },
         "Content": [
            "Contenu"
         ],
         "Potato": [
            "Patate",
            "Patates"
         ]
      }
   }
}
```

I traced the error to `parse.js`. I can create a pull request for this, but first, I would like to know if the current output is only an error for the Jed format, or if it is also an error for the RAW format?

**Comment by mikeedwards** [comment]
Hmm, which version of Jed are you using?

**Comment by patrickfournier** [comment]
1.1.0

**Comment by patrickfournier** [comment]
I just saw the doc on https://www.npmjs.com/package/po2json and I see there is a jed1.x format (this was not listed in the `po2json --help`). It works with this format.

Sorry about that.

**Comment by mikeedwards** [comment]
Ah, ok. There was a breaking change in that version of Jed. Try running `po2json` with the format set to `jed1.x` (as opposed to `raw`, `mf` or just `jed`). We had to make a special case to deal with Jed >= 1.1.0. Take a peek here under the `--format` option for more on that https://github.com/mikeedwards/po2json#methods

**Comment by mikeedwards** [comment]
Ah, beat me to it! Thanks for reporting the problem--I'll try to make the documentation clearer regarding the 1.1.0 issue.

**Comment by patrickfournier** [comment]
Thanks!

**Comment by megaboich** [comment]
Hi mikeedwards, 

I also had encountered this problem, and yes, in documentation there is a description for `jed1.x` but in the example still `jed` is used. So it happened that first I noticed example, so I was sure that `jed` is what we need to specify to work with latest version of `jed`.
Really, `jed1.x` looks like a thing for old compatibility, but it is for latest version.

Probably it might be a good idea to update example to use `jed1.x` instead of `jed` so people who likes to do copy-paste will not end up in trouble.

**Comment by aheissenberger** [comment]
[Wordpress i18n support for Javascript](https://developer.wordpress.org/block-editor/how-to-guides/internationalization/) requires `-f jed1.x` to work correctly!
