### ISSUE TITLE
import error po2json

### ISSUE THREAD

**Issue by aaeronn** [mikeedwards/po2json#48]
I am using react and webpack. 
I am trying to import po2json like:

var po2json = require('po2json')

but it is giving me error like:

ERROR in ./~/po2json/lib/parseFile.js
Module not found: Error: Cannot resolve module 'fs' in /home/anonymous/project/node_modules/po2json/lib

Why I am getting this error ?

But no error on importing Jed

var Jed = require('jed')
##

**Comment by mikeedwards** [comment]
Hmm, interesting. Check out this comment from another module. It may be the same problem between `webpack` and `fs` for browser builds:

https://github.com/webpack/jade-loader/issues/8#issuecomment-55568520

**Comment by mikeedwards** [comment]
Are you still having trouble with this? If not, I'll close the ticket.
