### ISSUE TITLE
How do I actually save the output?

### ISSUE THREAD

**Issue by blaasvaer** [mikeedwards/po2json#62]
I get [object Object] no matter whether i parse the buffer or not. I see the content when I output the buffer to the console. But can't get it into a proper file.

```
po2json.parseFile('./source/da.po', function ( err, buffer ) {
	var jsonData = po2json.parse(buffer);

	fs.writeFile('translation.json', jsonData );
```

also tried:

	`fs.writeFile('translation.json', JSON.stringify( jsonData ) );`

gives empty object.

**Comment by blaasvaer** [comment]
Well, and then I found parseFile ... but the docs throw me of. I there any (complete) example of how to read a .po file and save it to .json format without all the guessing?

**Comment by blaasvaer** [comment]
Well, found »gulp-po2json«. Problem solved.

**Comment by mikeedwards** [comment]
Great! Yeah, we've been fortunate that there are a lot of projects like `gulp-po2json` that assist with tasks like this for almost any framework, library, etc. Let me know if there's anything else you need, though.
