### ISSUE TITLE
fuzzy and comments in po disappear on json.

### ISSUE THREAD

**Issue by altsanz** [mikeedwards/po2json#70]
### Expected Behavior
Fuzzy and comments are added on generated json.
### Actual Behavior
They are ignored

### Steps to Reproduce
po2json a file with po comments and fuzzy flags.

### Additional Data

Po file:
```
#: app\ui\apps\about\about.html
msgid "STR_test1"
msgstr "test1original"

#: app\ui\dashboard\app-area\app-area.html
msgid "STR_test2"
msgstr "test2original"

#: app\ui\apps\media-library\media-detail.html
#, fuzzy
msgid "test3"
msgstr "original"

#. This is a comment for translators.
#: test2
msgid "STR_JobStatus"
msgstr "Status"
```

Motivation: People may use JSON as middleware to convert to other formats, or build apps over json files, .. it's information on po file that's not being added.

**Comment by mikeedwards** [comment]
Hmm, this is interesting. What would the resulting JSON format look like?

**Comment by altsanz** [comment]
I can't figure out how to do it without breaking current JSON... My breaking proposal is this:

```json
{
    "STR_test1": {
        "fuzzy": true,
        "comment": "string whatever",
        "translation": [
            null,
            "test1translated"
        ]
    }
}
```

**Comment by mikeedwards** [comment]
If I ever get around to a 2.0, where I can make a ton of breaking changes, I might take a crack at this. It's a good suggestion.
