### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by rhblind** [mikeedwards/po2json#72]
This library is GPL v2 licensed. When bundled in a front end application this will trigger clauses in the license which will force us to GPL license our frontend application, as we are effectively redistributing the source code by transferring it to the clients browser.

Is this intentional, or would it be possible to evaluate alternate licenses in able to let people use this library in front end applications?

Other than that, thanks for the great library!

**Comment by mikeedwards** [comment]
Sorry for getting to this late. I actually hadn't considered the frontend case, since it was intended initially for the backend. What kind of license would help? LGPL?

**Comment by rhblind** [comment]
Hi thanks for reply. Any kind of license which doesn't require the user to open source their project if the library is redistributed in it. I usually use [Apache v2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) or [MIT](https://tldrlegal.com/license/mit-license) licenses, but you should choose a license based on your intent with the library.

**Comment by mikeedwards** [comment]
Fixed (at last!) by using `LGPL-2.0-or-later`
