### ISSUE TITLE
Version 1 alpha taged as latest in NPM breaks stuff

### ISSUE THREAD

**Issue by maximelebastard** [mikeedwards/po2json#76]
Hi !

To begin with, thanks for this new version ! 

This new alpha version has been tagged as the latest version in npm. Some libraries like po-loader that uses this library has a dependency to `>= 0.4.0` so it uses the new alpha package.

As meant by the alpha tag, it probably has some bugs (see my other ticket) and it breaks po-loader.

Would you mind to tag the alpha version as next instead of latest in NPM ? 

### Expected Behavior
`npm install po2json` to not install an alpha version.

### Actual Behavior
`npm install po2json` installs an alpha version.

### Steps to Reproduce
Try to install po-loader and see which version of po2json is installed.

**Comment by creage** [comment]
Any progress on this issue?

**Comment by mikeedwards** [comment]
Finally updated this, thanks for your patience
