### ISSUE TITLE
Invalid executable file `bin/po2json` which bundled npm package

### ISSUE THREAD

**Issue by kamataryo** [mikeedwards/po2json#80]
### Expected Behavior

`node_modules/.bin/po2json` is executable.

### Actual Behavior

`node_modules/.bin/po2json` exits non-zero status and says:

```shell
$ ./po2json -h
env: node\r: No such file or directory
```

### Steps to Reproduce

`po2json` package version: 1.0.0-alpha

```shell
$ uname -a
Darwin Ciconia.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

$ node -v
v11.8.0

$ npm -v
6.5.0

$ yarn -v
1.13.0
```

### Additional Data

It seems to be a linebreak probrem.
If all `\r\n` replaced with `\n`, `po2json` works.
By the way, `npx po2json` works but I am not sure why.

**Comment by flexchar** [comment]
This should be easily fixable by updating linter settings. ;)

**Comment by kamataryo** [comment]
Yes, this have been fixed already. Thanks a lot!
